[project]
name = "central"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "locust>=2.41.6",
    "requests>=2.32.5",
]
